msg = This is from repo alien !  Production Profile

demo:
 properties:
  greet : Good Morning .You All Miserable Bastards !!! 
  smile : Do Me a Favour, Have some good Smile on your Fucking Face !!! 